# grafana/provisioning/datasources/prometheus.yml
#
# Declarative provisioning for the Prometheus datasource in Grafana.
# Implements part of REQ-1-083.

apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    # URL should point to the Kubernetes service for Prometheus.
    # The exact name may vary based on deployment (e.g., Helm chart values).
    url: http://prometheus-server.monitoring.svc.cluster.local:80
    isDefault: true
    jsonData:
      # Time interval for rate functions.
      timeInterval: "5s"
    editable: false