apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service-deployment
  namespace: platform
  labels:
    app: feed-service
spec:
  replicas: 2 # REQ-1-085 High Availability
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          # The image will be dynamically replaced by the CI/CD pipeline
          image: <aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/platform-service-feed:latest
          ports:
            - containerPort: 50052
              name: grpc
          envFrom:
            - configMapRef:
                name: feed-service-config
            - secretRef:
                name: feed-service-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            grpc:
              port: 50052
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            grpc:
              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 10
      terminationGracePeriodSeconds: 30