apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: platform
  labels:
    app: feed-service
spec:
  type: ClusterIP
  selector:
    app: feed-service
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
      protocol: TCP